apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: openebs
  namespace: kube-system
spec:
  repo: https://openebs.github.io/charts
  chart: openebs
  targetNamespace: openebs
  createNamespace: true
  valuesContent: |-
    localprovisioner:
      deviceClass:
        enabled: false
      hostpathClass:
        enabled: true
        isDefaultClass: true
        name: openebs-hostpath
