apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  namespace: flaresolverr
spec:
  type: ClusterIP
  clusterIP: 10.43.200.202
  ports:
    - port: 8191
      targetPort: 8191
      name: http
  selector:
    app: flaresolverr
