apiVersion: v1
kind: Service
metadata:
  name: jackett
  namespace: jackett
spec:
  type: ClusterIP
  clusterIP: 10.43.200.201
  ports:
    - port: 80
      targetPort: 9117
      name: http
  selector:
    app: jackett
