apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aiometadata-pvc
  namespace: aiometadata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiometadata
  namespace: aiometadata
spec:
  selector:
    matchLabels:
      app: aiometadata
  template:
    metadata:
      labels:
        app: aiometadata
    spec:
      containers:
        - name: aiometadata
          image: ghcr.io/cedya77/aiometadata:latest
          ports:
            - containerPort: 3232
              # hostPort: 3232
          envFrom:
            - configMapRef:
                name: aiometadata-env
          volumeMounts:
            - name: aiometadata-data
              mountPath: /app/addon/data
      volumes:
        - name: aiometadata-data
          persistentVolumeClaim:
            claimName: aiometadata-pvc
