apiVersion: v1
kind: Service
metadata:
  name: aiometadata
  namespace: aiometadata
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3232
      name: http
  selector:
    app: aiometadata
