apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiostreams
  namespace: aiostreams
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiostreams
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: aiostreams
    spec:
      containers:
        - name: aiostreams
          image: ghcr.io/viren070/aiostreams:latest
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: PORT
              value: "3000"
            - name: LOG_LEVEL
              value: "info"
          envFrom:
            - configMapRef:
                name: aiostreams-env
            - secretRef:
                name: aiostreams-secret-env

            # Add other environment variables here if needed
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: aiostreams-data-longhorn
