apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aiostreams
  namespace: aiostreams
spec:
  rules:
    - host: aiostreams.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aiostreams
                port:
                  number: 3000
